# Handling Reading
exclude: [
  'bower_components',
  'node_modules',
  'src',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  '*.sublime-project',
  'package.json' ]

# Conversion
# markdown:    kramdown
# highlighter: rouge
# lsi:         false
# excerpt_separator: "\n\n"

# Outputting
permalink:  none

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

#Markdown Processors
redcarpet:
  extensions: []

kramdown:
  input: GFM
