sitename: Jeffrey Naval
description: Developer Journal

# Handling Reading
exclude:
  - bower_components
  - node_modules
  - src
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - '*.sublime-project'
  - package.json'

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

permalink: /:title/

# Conversion
markdown: redcarpet
highlighter: pygments
